### ISSUE TITLE
Should file coq-lib/lem_string.v be generated or not?

### ISSUE THREAD

**Issue by rmn30** [rems-project/lem#11]
The file coq-lib/lem_string.v is checked in to git while other lem-generated coq files are not. Looking at the [history](https://github.com/rems-project/lem/commits/master/coq-lib/lem_string.v) of the file it looks like Dom made some (manual?) edits to it at some point in the past but these were overwritten by generated output. The question is: are the edits still relevant and if so should we prevent lem from overwritting this file?

**Comment by bacam** [comment]
We should remove the generated file, because 5ec58c483242851b2a8d1289ffb953074b34920e changed the relevant Lem definition so that it doesn't need a measure in Coq.  I'll double check this and commit shortly.
