### ISSUE TITLE
 spell wrong from lintian check

### ISSUE THREAD

**Issue by yuzibo** [rems-project/lem#33]
Hi,

When I am trying to package the tool to Debian and I get the warning from Debian lintian tool:

```bash
I: lem: spelling-error-in-binary maching matching [usr/bin/lem]
I: lem: spelling-error-in-binary overriden overridden [usr/bin/lem]
I: lem: spelling-error-in-binary separatly separately [usr/bin/lem]
```
The last one is the easiest to fix, it just was existed in one source file:

```bash
--- a/src/main.ml
+++ b/src/main.ml
@@ -110,7 +110,7 @@
     " generate OCaml");
   ( "-tex",
     Arg.Unit (add_backend (Target.Target_no_ident Target.Target_tex)),
-    " generate LaTeX for each module separatly");
+    " generate LaTeX for each module separately");
   ( "-tex_all",
     Arg.String (fun fn -> tex_all_filename_opt := Some fn),
     " generate LaTeX in a single file");

```
But if `grep` with `maching` and ` overriden`, there are too verbose under the repo. Is it value to change these? and I thought some false positives in there.

**Comment by yuzibo** [comment]
For `maching` warning:
`| Let_def(_,_,_) ->
                  raise (Reporting_basic.err_unreachable l "Fancy, top level pattern maching should not have a class constraint. Typechecking should have complained.")` 
The code in lem binary is [here](https://github.com/rems-project/lem/blob/master/src/def_trans.ml#L522)
Could you help me to confirm this? 

For `overriden` warning, there are too many for this.

**Comment by bacam** [comment]
Thanks, I've corrected those.

**Comment by yuzibo** [comment]
Thanks~
